site_name: labelCloud
repo_url: https://github.com/ch-sa/labelCloud
copyright: "&copy; Christoph Sager & Contributers"

nav:
    - 'index.md'
    - 'setup.md'
    - 'configuration.md'
    - 'shortcuts.md'
    - 'conventions.md'

theme:
  name: material
  logo: assets/logo.png

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ch-sa
    - icon: fontawesome/brands/linkedin
      link: https://de.linkedin.com/in/christophsager
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/ch_sager